import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  data: [
    // === FSRU ===
    {
      id: 2101,
      uraian: "Project Management FSRU",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 4000000000,
      totalHarga: 4000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT",
      tahun: 2023,
      proyek: "FSRU Jakarta",
      lokasi: "Jakarta",
      tipe: "FSRU",
      kategori: "Material Konstruksi"
    },
    {
      id: 2102,
      uraian: "Pompa FSRU",
      satuan: "Unit",
      qty: 2,
      hargaSatuan: 1500000000,
      totalHarga: 3000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PERALATAN",
      tahun: 2023,
      proyek: "FSRU Jakarta",
      lokasi: "Jakarta",
      tipe: "FSRU",
      kategori: "Peralatan"
    },
    {
      id: 2103,
      uraian: "Upah Operator FSRU",
      satuan: "Orang",
      qty: 8,
      hargaSatuan: 800000,
      totalHarga: 6400000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      proyek: "FSRU Jakarta",
      lokasi: "Jakarta",
      tipe: "FSRU",
      kategori: "Upah"
    },
    {
      id: 2104,
      uraian: "Jasa Konsultan FSRU",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 20000000,
      totalHarga: 20000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      proyek: "FSRU Jakarta",
      lokasi: "Jakarta",
      tipe: "FSRU",
      kategori: "Jasa"
    },
    {
      id: 2105,
      uraian: "Testing FSRU",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 30000000,
      totalHarga: 30000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      proyek: "FSRU Jakarta",
      lokasi: "Jakarta",
      tipe: "FSRU",
      kategori: "Testing"
    },
    // === ORF ===
    {
      id: 2201,
      uraian: "Project Management ORF",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 3500000000,
      totalHarga: 3500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT",
      tahun: 2023,
      proyek: "ORF Surabaya",
      lokasi: "Surabaya",
      tipe: "ORF",
      kategori: "Material Konstruksi"
    },
    {
      id: 2202,
      uraian: "Pompa ORF",
      satuan: "Unit",
      qty: 1,
      hargaSatuan: 1200000000,
      totalHarga: 1200000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PERALATAN",
      tahun: 2023,
      proyek: "ORF Surabaya",
      lokasi: "Surabaya",
      tipe: "ORF",
      kategori: "Peralatan"
    },
    {
      id: 2203,
      uraian: "Upah Operator ORF",
      satuan: "Orang",
      qty: 5,
      hargaSatuan: 700000,
      totalHarga: 3500000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      proyek: "ORF Surabaya",
      lokasi: "Surabaya",
      tipe: "ORF",
      kategori: "Upah"
    },
    {
      id: 2204,
      uraian: "Jasa Konsultan ORF",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 15000000,
      totalHarga: 15000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      proyek: "ORF Surabaya",
      lokasi: "Surabaya",
      tipe: "ORF",
      kategori: "Jasa"
    },
    {
      id: 2205,
      uraian: "Testing ORF",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 20000000,
      totalHarga: 20000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      proyek: "ORF Surabaya",
      lokasi: "Surabaya",
      tipe: "ORF",
      kategori: "Testing"
    },
    // === OTS ===
    {
      id: 2301,
      uraian: "Project Management OTS",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 3200000000,
      totalHarga: 3200000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT",
      tahun: 2023,
      proyek: "OTS Makassar",
      lokasi: "Makassar",
      tipe: "OTS",
      kategori: "Material Konstruksi"
    },
    {
      id: 2302,
      uraian: "Pompa OTS",
      satuan: "Unit",
      qty: 1,
      hargaSatuan: 1000000000,
      totalHarga: 1000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PERALATAN",
      tahun: 2023,
      proyek: "OTS Makassar",
      lokasi: "Makassar",
      tipe: "OTS",
      kategori: "Peralatan"
    },
    {
      id: 2303,
      uraian: "Upah Operator OTS",
      satuan: "Orang",
      qty: 4,
      hargaSatuan: 650000,
      totalHarga: 2600000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      proyek: "OTS Makassar",
      lokasi: "Makassar",
      tipe: "OTS",
      kategori: "Upah"
    },
    {
      id: 2304,
      uraian: "Jasa Konsultan OTS",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 12000000,
      totalHarga: 12000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      proyek: "OTS Makassar",
      lokasi: "Makassar",
      tipe: "OTS",
      kategori: "Jasa"
    },
    {
      id: 2305,
      uraian: "Testing OTS",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 18000000,
      totalHarga: 18000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      proyek: "OTS Makassar",
      lokasi: "Makassar",
      tipe: "OTS",
      kategori: "Testing"
    },
    // === ORU ===
    {
      id: 2401,
      uraian: "Project Management ORU",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 3100000000,
      totalHarga: 3100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT",
      tahun: 2023,
      proyek: "ORU Bali",
      lokasi: "Bali",
      tipe: "ORU",
      kategori: "Material Konstruksi"
    },
    {
      id: 2402,
      uraian: "Pompa ORU",
      satuan: "Unit",
      qty: 1,
      hargaSatuan: 900000000,
      totalHarga: 900000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PERALATAN",
      tahun: 2023,
      proyek: "ORU Bali",
      lokasi: "Bali",
      tipe: "ORU",
      kategori: "Peralatan"
    },
    {
      id: 2403,
      uraian: "Upah Operator ORU",
      satuan: "Orang",
      qty: 3,
      hargaSatuan: 600000,
      totalHarga: 1800000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      proyek: "ORU Bali",
      lokasi: "Bali",
      tipe: "ORU",
      kategori: "Upah"
    },
    {
      id: 2404,
      uraian: "Jasa Konsultan ORU",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 10000000,
      totalHarga: 10000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      proyek: "ORU Bali",
      lokasi: "Bali",
      tipe: "ORU",
      kategori: "Jasa"
    },
    {
      id: 2405,
      uraian: "Testing ORU",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 15000000,
      totalHarga: 15000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      proyek: "ORU Bali",
      lokasi: "Bali",
      tipe: "ORU",
      kategori: "Testing"
    },
  ],
  filterTipe: "FSRU", // Tab aktif: FSRU, ORF, OTS, ORU
  filterKategori: [],
  search: "",
};

const receivingTerminalSlice = createSlice({
  name: "receivingTerminal",
  initialState,
  reducers: {
    setFilterTipe: (state, action) => {
      state.filterTipe = action.payload;
    },
    setFilterKategori: (state, action) => {
      state.filterKategori = action.payload;
    },
    setSearch: (state, action) => {
      state.search = action.payload;
    },
  },
});

export const { setFilterTipe, setFilterKategori, setSearch } = receivingTerminalSlice.actions;

export default receivingTerminalSlice.reducer;
