import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  data: [
    // === LNGC ===
    {
      id: 2001,
      uraian: "Project Management LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 3500000000,
      totalHarga: 3500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC",
      kategori: "Material Konstruksi"
    },
    {
      id: 2002,
      uraian: "Hull Plate",
      satuan: "Ton",
      qty: 2000,
      hargaSatuan: 12000000,
      totalHarga: 24000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC",
      kategori: "Peralatan"
    },
    {
      id: 2003,
      uraian: "Upah Tukang Las",
      satuan: "Orang",
      qty: 10,
      hargaSatuan: 500000,
      totalHarga: 5000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC",
      kategori: "Upah"
    },
    {
      id: 2004,
      uraian: "Jasa Surveyor",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 10000000,
      totalHarga: 10000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC",
      kategori: "Jasa"
    },
    {
      id: 2005,
      uraian: "Testing Kapal",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 20000000,
      totalHarga: 20000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC",
      kategori: "Testing"
    },
    // === LNG Barge ===
    {
      id: 3001,
      uraian: "Project Management LNG Barge",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 2500000000,
      totalHarga: 2500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "LNG Barge 50.000 m³",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Barge Batam",
      lokasi: "Batam",
      tipe: "LNG Barge",
      kategori: "Material Konstruksi"
    },
    {
      id: 3002,
      uraian: "Main Engine",
      satuan: "Unit",
      qty: 2,
      hargaSatuan: 800000000,
      totalHarga: 1600000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PERALATAN",
      tahun: 2023,
      infrastruktur: "LNG Barge 50.000 m³",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Barge Batam",
      lokasi: "Batam",
      tipe: "LNG Barge",
      kategori: "Peralatan"
    },
    {
      id: 3003,
      uraian: "Upah Tukang Cat",
      satuan: "Orang",
      qty: 5,
      hargaSatuan: 400000,
      totalHarga: 2000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      infrastruktur: "LNG Barge 50.000 m³",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Barge Batam",
      lokasi: "Batam",
      tipe: "LNG Barge",
      kategori: "Upah"
    },
    {
      id: 3004,
      uraian: "Jasa Konsultan",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 15000000,
      totalHarga: 15000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      infrastruktur: "LNG Barge 50.000 m³",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Barge Batam",
      lokasi: "Batam",
      tipe: "LNG Barge",
      kategori: "Jasa"
    },
    {
      id: 3005,
      uraian: "Testing Barge",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 10000000,
      totalHarga: 10000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      infrastruktur: "LNG Barge 50.000 m³",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Barge Batam",
      lokasi: "Batam",
      tipe: "LNG Barge",
      kategori: "Testing"
    },
    // === LNG Trucking ===
    {
      id: 4001,
      uraian: "Project Management LNG Trucking",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 1000000000,
      totalHarga: 1000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "LNG Trucking 100 CBM",
      volume: 100,
      satuanVolume: "CBM",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Trucking Jakarta",
      lokasi: "Jakarta",
      tipe: "LNG Trucking",
      kategori: "Material Konstruksi"
    },
    {
      id: 4002,
      uraian: "Truk Tangki",
      satuan: "Unit",
      qty: 10,
      hargaSatuan: 700000000,
      totalHarga: 7000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PERALATAN",
      tahun: 2023,
      infrastruktur: "LNG Trucking 100 CBM",
      volume: 100,
      satuanVolume: "CBM",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Trucking Jakarta",
      lokasi: "Jakarta",
      tipe: "LNG Trucking",
      kategori: "Peralatan"
    },
    {
      id: 4003,
      uraian: "Upah Sopir",
      satuan: "Orang",
      qty: 10,
      hargaSatuan: 300000,
      totalHarga: 3000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "UPAH",
      tahun: 2023,
      infrastruktur: "LNG Trucking 100 CBM",
      volume: 100,
      satuanVolume: "CBM",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Trucking Jakarta",
      lokasi: "Jakarta",
      tipe: "LNG Trucking",
      kategori: "Upah"
    },
    {
      id: 4004,
      uraian: "Jasa Maintenance",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 5000000,
      totalHarga: 5000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "JASA",
      tahun: 2023,
      infrastruktur: "LNG Trucking 100 CBM",
      volume: 100,
      satuanVolume: "CBM",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Trucking Jakarta",
      lokasi: "Jakarta",
      tipe: "LNG Trucking",
      kategori: "Jasa"
    },
    {
      id: 4005,
      uraian: "Testing Truk",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 2000000,
      totalHarga: 2000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "TESTING",
      tahun: 2023,
      infrastruktur: "LNG Trucking 100 CBM",
      volume: 100,
      satuanVolume: "CBM",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNG Trucking Jakarta",
      lokasi: "Jakarta",
      tipe: "LNG Trucking",
      kategori: "Testing"
    },
  ],
  filterTipe: "LNGC", // Tab aktif: LNGC, LNG Barge, LNG Trucking
  filterKategori: [], // Array: Material Konstruksi, Peralatan, Upah, Jasa, Testing
  search: "",
};

const transportSlice = createSlice({
  name: "transport",
  initialState,
  reducers: {
    setFilterTipe: (state, action) => {
      state.filterTipe = action.payload;
    },
    setFilterKategori: (state, action) => {
      state.filterKategori = action.payload;
    },
    setSearch: (state, action) => {
      state.search = action.payload;
    },
  },
});

export const { setFilterTipe, setFilterKategori, setSearch } = transportSlice.actions;

export default transportSlice.reducer;
