import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  costs: [
    // === PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN ===
    {
      id: 1,
      uraian: "Project Management",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 1154296598,
      totalHarga: 1154296598,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 2,
      uraian: "Ijin MIGAS -  Certificate of Inspection (COI) PSV",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 25000000,
      totalHarga: 25000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 3,
      uraian: "Ijin Lingkungan",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 4,
      uraian: "Ijin Mendirikan Bangunan (IMB)",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 205500801,
      totalHarga: 205500801,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // === SUPPORTING WORK ===
    {
      id: 5,
      uraian: "Pekerjaan Soil Investigation + Laporan + Penentuan Kedalaman Pondasi",
      satuan: "Titik",
      qty: 1,
      hargaSatuan: 104250933.15,
      totalHarga: 104250933.15,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 6,
      uraian: "Pekerjaan Survey Lokasi dan Pembuatan Gambar",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 6728996.86,
      totalHarga: 6728996.86,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PENYEDIAAN MATERIAL ===
    {
      id: 100,
      uraian: "Line Pipe, CS, ASME B36.10, ASTM A106, Sch 80, Gr.B, Bare Pipe, PE, Seamless, DRL, Dia. 1/2\"",
      satuan: "M'",
      qty: 12,
      hargaSatuan: 118797.35,
      totalHarga: 1425568.15,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN ===
    {
      id: 200,
      uraian: "Pekerjaan Pengelasan Line Up Pipa Baja Diameter s.d 2\"",
      satuan: "Joint",
      qty: 17,
      hargaSatuan: 552365.49,
      totalHarga: 9390213.41,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN KHUSUS/FINISHING ===
    {
      id: 300,
      uraian: "Dismantling Eksisting Filter",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 177300000,
      totalHarga: 177300000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN KHUSUS/FINISHING",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN DOKUMENTASI ===
    {
      id: 400,
      uraian: "Pekerjaan Laporan Harian",
      satuan: "hari",
      qty: 210,
      hargaSatuan: 75456.49,
      totalHarga: 15845863.16,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION ===
    {
      id: 500,
      uraian: "Pekerjaan Commissioning & Fasilitas Penanganan Keselamatan Kerja",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 51022814.02,
      totalHarga: 51022814.02,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    
    // === MID SCALE LNG FSRU ===
    {
      id: 11001,
      uraian: "Project Management FSRU MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 900000000,
      totalHarga: 900000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    {
      id: 11002,
      uraian: "Ijin MIGAS - Certificate of Inspection (COI) PSV MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 20000000,
      totalHarga: 20000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    {
      id: 11003,
      uraian: "Ijin Lingkungan MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 80000000,
      totalHarga: 80000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    {
      id: 11004,
      uraian: "Ijin Mendirikan Bangunan (IMB) MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 150000000,
      totalHarga: 150000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    // === SUPPORTING WORK MID ===
    {
      id: 11005,
      uraian: "Pekerjaan Soil Investigation MID",
      satuan: "Titik",
      qty: 1,
      hargaSatuan: 80000000,
      totalHarga: 80000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    {
      id: 11006,
      uraian: "Pekerjaan Survey Lokasi dan Pembuatan Gambar MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 5000000,
      totalHarga: 5000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    // === PENYEDIAAN MATERIAL MID ===
    {
      id: 11100,
      uraian: "Line Pipe MID",
      satuan: "M'",
      qty: 10,
      hargaSatuan: 100000,
      totalHarga: 1000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN MID ===
    {
      id: 11200,
      uraian: "Pekerjaan Pengelasan MID",
      satuan: "Joint",
      qty: 10,
      hargaSatuan: 400000,
      totalHarga: 4000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    // === PEKERJAAN KHUSUS/FINISHING MID ===
    {
      id: 11300,
      uraian: "Dismantling Eksisting Filter MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN KHUSUS/FINISHING",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    // === PEKERJAAN DOKUMENTASI MID ===
    {
      id: 11400,
      uraian: "Pekerjaan Laporan Harian MID",
      satuan: "hari",
      qty: 100,
      hargaSatuan: 50000,
      totalHarga: 5000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION MID ===
    {
      id: 11500,
      uraian: "Pekerjaan Commissioning MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 30000000,
      totalHarga: 30000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG FSRU [50.000 - 150.000 m³]",
      volume: 100000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 100,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Mid Example",
      lokasi: "Jawa Tengah",
      tipe: "FSRU"
    },

    // === SMALL SCALE LNG FSRU ===
    {
      id: 12001,
      uraian: "Project Management FSRU SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 500000000,
      totalHarga: 500000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    {
      id: 12002,
      uraian: "Ijin MIGAS - Certificate of Inspection (COI) PSV SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 10000000,
      totalHarga: 10000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    {
      id: 12003,
      uraian: "Ijin Lingkungan SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 40000000,
      totalHarga: 40000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    {
      id: 12004,
      uraian: "Ijin Mendirikan Bangunan (IMB) SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 70000000,
      totalHarga: 70000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    // === SUPPORTING WORK SMALL ===
    {
      id: 12005,
      uraian: "Pekerjaan Soil Investigation SMALL",
      satuan: "Titik",
      qty: 1,
      hargaSatuan: 40000000,
      totalHarga: 40000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    {
      id: 12006,
      uraian: "Pekerjaan Survey Lokasi dan Pembuatan Gambar SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 2500000,
      totalHarga: 2500000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    // === PENYEDIAAN MATERIAL SMALL ===
    {
      id: 12100,
      uraian: "Line Pipe SMALL",
      satuan: "M'",
      qty: 5,
      hargaSatuan: 80000,
      totalHarga: 400000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN SMALL ===
    {
      id: 12200,
      uraian: "Pekerjaan Pengelasan SMALL",
      satuan: "Joint",
      qty: 5,
      hargaSatuan: 200000,
      totalHarga: 1000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    // === PEKERJAAN KHUSUS/FINISHING SMALL ===
    {
      id: 12300,
      uraian: "Dismantling Eksisting Filter SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 50000000,
      totalHarga: 50000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN KHUSUS/FINISHING",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    // === PEKERJAAN DOKUMENTASI SMALL ===
    {
      id: 12400,
      uraian: "Pekerjaan Laporan Harian SMALL",
      satuan: "hari",
      qty: 50,
      hargaSatuan: 30000,
      totalHarga: 1500000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION SMALL ===
    {
      id: 12500,
      uraian: "Pekerjaan Commissioning SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 15000000,
      totalHarga: 15000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG FSRU [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 30,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Small Example",
      lokasi: "Sumatera Selatan",
      tipe: "FSRU"
    },

    // === DUMMY DATA: LNG PLANT ===
    {
      id: 1001,
      uraian: "Project Management LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 2100000000,
      totalHarga: 2100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    {
      id: 1002,
      uraian: "Ijin Lingkungan LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 150000000,
      totalHarga: 150000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === SUPPORTING WORK LNG PLANT ===
    {
      id: 1003,
      uraian: "Soil Investigation LNG Plant",
      satuan: "Titik",
      qty: 2,
      hargaSatuan: 90000000,
      totalHarga: 180000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PENYEDIAAN MATERIAL LNG PLANT ===
    {
      id: 1004,
      uraian: "Main Cryogenic Pipe",
      satuan: "m",
      qty: 100,
      hargaSatuan: 2500000,
      totalHarga: 250000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN LNG PLANT ===
    {
      id: 1005,
      uraian: "Pemasangan Equipment Utama",
      satuan: "Unit",
      qty: 5,
      hargaSatuan: 120000000,
      totalHarga: 600000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PEKERJAAN DOKUMENTASI LNG PLANT ===
    {
      id: 1006,
      uraian: "Dokumentasi Proyek LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 50000000,
      totalHarga: 50000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION LNG PLANT ===
    {
      id: 1007,
      uraian: "Commissioning LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 80000000,
      totalHarga: 80000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    
    // === DUMMY DATA: LNGC ===
    {
      id: 2001,
      uraian: "Project Management LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 3500000000,
      totalHarga: 3500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    {
      id: 2002,
      uraian: "Ijin Lingkungan LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 200000000,
      totalHarga: 200000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === SUPPORTING WORK LNGC ===
    {
      id: 2003,
      uraian: "Docking & Survey Kapal",
      satuan: "Kapal",
      qty: 1,
      hargaSatuan: 500000000,
      totalHarga: 500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PENYEDIAAN MATERIAL LNGC ===
    {
      id: 2004,
      uraian: "Hull Plate",
      satuan: "Ton",
      qty: 2000,
      hargaSatuan: 12000000,
      totalHarga: 24000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN LNGC ===
    {
      id: 2005,
      uraian: "Pemasangan Mesin Utama",
      satuan: "Unit",
      qty: 2,
      hargaSatuan: 800000000,
      totalHarga: 1600000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PEKERJAAN DOKUMENTASI LNGC ===
    {
      id: 2006,
      uraian: "Dokumentasi Kapal LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION LNGC ===
    {
      id: 2007,
      uraian: "Commissioning Kapal LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 150000000,
      totalHarga: 150000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === MID SCALE LNGC ===
    {
      id: 21001,
      uraian: "Project Management LNGC MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 2000000000,
      totalHarga: 2000000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },
    {
      id: 21002,
      uraian: "Ijin Lingkungan LNGC MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },
    {
      id: 21003,
      uraian: "Docking & Survey Kapal LNGC MID",
      satuan: "Kapal",
      qty: 1,
      hargaSatuan: 250000000,
      totalHarga: 250000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },
    {
      id: 21100,
      uraian: "Hull Plate LNGC MID",
      satuan: "Ton",
      qty: 800,
      hargaSatuan: 11000000,
      totalHarga: 8800000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },
    {
      id: 21200,
      uraian: "Pemasangan Mesin Utama LNGC MID",
      satuan: "Unit",
      qty: 1,
      hargaSatuan: 400000000,
      totalHarga: 400000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },
    {
      id: 21300,
      uraian: "Dokumentasi Kapal LNGC MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 50000000,
      totalHarga: 50000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },
    {
      id: 21400,
      uraian: "Pekerjaan Commissioning LNGC MID",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 70000000,
      totalHarga: 70000000,
      aaceClass: 3,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "MID SCALE LNG CARRIER (LNGC) [30.000 - 100.000 m³]",
      volume: 50000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Mid Example",
      lokasi: "Jawa Barat",
      tipe: "LNGC"
    },

    // === SMALL SCALE LNGC ===
    {
      id: 22001,
      uraian: "Project Management LNGC SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 1000000000,
      totalHarga: 1000000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
    {
      id: 22002,
      uraian: "Ijin Lingkungan LNGC SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 50000000,
      totalHarga: 50000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
    {
      id: 22003,
      uraian: "Docking & Survey Kapal LNGC SMALL",
      satuan: "Kapal",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
    {
      id: 22100,
      uraian: "Hull Plate LNGC SMALL",
      satuan: "Ton",
      qty: 300,
      hargaSatuan: 10000000,
      totalHarga: 3000000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
    {
      id: 22200,
      uraian: "Pemasangan Mesin Utama LNGC SMALL",
      satuan: "Unit",
      qty: 1,
      hargaSatuan: 200000000,
      totalHarga: 200000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
    {
      id: 22300,
      uraian: "Dokumentasi Kapal LNGC SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 25000000,
      totalHarga: 25000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
    {
      id: 22400,
      uraian: "Pekerjaan Commissioning LNGC SMALL",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 35000000,
      totalHarga: 35000000,
      aaceClass: 4,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "SMALL SCALE LNG CARRIER (LNGC) [< 30.000 m³]",
      volume: 20000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Small Example",
      lokasi: "Kalimantan Timur",
      tipe: "LNGC"
    },
  ],
  filterJenis: null,
};

const constractionCostSlice = createSlice({
  name: 'constractionCost',
  initialState,
  reducers: {
    setFilterJenis: (state, action) => {
      state.filterJenis = action.payload;
    },
    addProjectCosts: (state, action) => {
      // action.payload: array of items
      // Cari id terakhir yang ada
      let maxId = state.costs.length > 0 ? Math.max(...state.costs.map(item => item.id || 0)) : 0;
      // Tambahkan data baru dengan id unik (incremental)
      const itemsWithUniqueId = action.payload.map((item, idx) => ({
        ...item,
        id: maxId + idx + 1,
      }));
      state.costs = [...state.costs, ...itemsWithUniqueId];
    },
    // reducer lain jika diperlukan
  },
});

export const { setFilterJenis, addProjectCosts } = constractionCostSlice.actions;
export default constractionCostSlice.reducer;
