import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  costs: [
    {
      id: 1,
      name: "LNG Plant A",
      jenis: "LNG Plant",
      kategori: "5k",
      lokasi: "Bali",
      tahun: 2026,
      levelAACE: 5,
      harga: 3000000,
    },
    {
      id: 2,
      name: "Transportasi B",
      jenis: "Transportasi",
      kategori: "10k",
      lokasi: "Jakarta",
      tahun: 2025,
      levelAACE: 4,
      harga: 5000000,
    },
    {
      id: 3,
      name: "ORF C",
      jenis: "ORF",
      kategori: "8k",
      lokasi: "Surabaya",
      tahun: 2024,
      levelAACE: 3,
      harga: 4000000,
    },
    {
      id: 4,
      name: "LNG Plant B",
      jenis: "LNG Plant",
      kategori: "10k",
      lokasi: "Makassar",
      tahun: 2027,
      levelAACE: 4,
      harga: 8000000,
    },
    {
      id: 5,
      name: "Transportasi C",
      jenis: "Transportasi",
      kategori: "15k",
      lokasi: "Medan",
      tahun: 2026,
      levelAACE: 3,
      harga: 6000000,
    },
    {
      id: 6,
      name: "Receiving Terminal D",
      jenis: "Receiving Terminal",
      kategori: "20k",
      lokasi: "Semarang",
      tahun: 2025,
      levelAACE: 5,
      harga: 9000000,
    },
    {
      id: 7,
      name: "Offtake Station E",
      jenis: "Offtake Station",
      kategori: "12k",
      lokasi: "Bandung",
      tahun: 2024,
      levelAACE: 4,
      harga: 7000000,
    },
    {
      id: 8,
      name: "ORF F",
      jenis: "ORF",
      kategori: "7k",
      lokasi: "Palembang",
      tahun: 2023,
      levelAACE: 3,
      harga: 3500000,
    },
    {
      id: 9,
      name: "Transmission Pipeline G",
      jenis: "Transmission Pipeline",
      kategori: "30k",
      lokasi: "Balikpapan",
      tahun: 2026,
      levelAACE: 5,
      harga: 15000000,
    },
    {
      id: 10,
      name: "Material & Package H",
      jenis: "Material & Package",
      kategori: "2k",
      lokasi: "Batam",
      tahun: 2025,
      levelAACE: 2,
      harga: 2000000,
    },
    {
      id: 11,
      name: "Receiving Terminal I",
      jenis: "Receiving Terminal",
      kategori: "25k",
      lokasi: "Pontianak",
      tahun: 2027,
      levelAACE: 4,
      harga: 11000000,
    },
    {
      id: 12,
      name: "Offtake Station J",
      jenis: "Offtake Station",
      kategori: "18k",
      lokasi: "Solo",
      tahun: 2026,
      levelAACE: 3,
      harga: 8000000,
    },
    {
      id: 13,
      name: "Transmission Pipeline K",
      jenis: "Transmission Pipeline",
      kategori: "40k",
      lokasi: "Cirebon",
      tahun: 2028,
      levelAACE: 5,
      harga: 20000000,
    },
    {
      id: 14,
      name: "Material & Package L",
      jenis: "Material & Package",
      kategori: "3k",
      lokasi: "Padang",
      tahun: 2024,
      levelAACE: 2,
      harga: 2500000,
    },
  ],
  filterJenis: null,
};

const constractionCostSlice = createSlice({
  name: 'constractionCost',
  initialState,
  reducers: {
    setFilterJenis: (state, action) => {
      state.filterJenis = action.payload;
    },
    // reducer lain jika diperlukan
  },
});

export const { setFilterJenis } = constractionCostSlice.actions;
export default constractionCostSlice.reducer;
