import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  costs: [
    // === PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN ===
    {
      id: 1,
      uraian: "Project Management",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 1154296598,
      totalHarga: 1154296598,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 2,
      uraian: "Ijin MIGAS -  Certificate of Inspection (COI) PSV",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 25000000,
      totalHarga: 25000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 3,
      uraian: "Ijin Lingkungan",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 4,
      uraian: "Ijin Mendirikan Bangunan (IMB)",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 205500801,
      totalHarga: 205500801,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // === SUPPORTING WORK ===
    {
      id: 5,
      uraian: "Pekerjaan Soil Investigation + Laporan + Penentuan Kedalaman Pondasi",
      satuan: "Titik",
      qty: 1,
      hargaSatuan: 104250933.15,
      totalHarga: 104250933.15,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 6,
      uraian: "Pekerjaan Survey Lokasi dan Pembuatan Gambar",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 6728996.86,
      totalHarga: 6728996.86,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PENYEDIAAN MATERIAL ===
    {
      id: 100,
      uraian: "Line Pipe, CS, ASME B36.10, ASTM A106, Sch 80, Gr.B, Bare Pipe, PE, Seamless, DRL, Dia. 1/2\"",
      satuan: "M'",
      qty: 12,
      hargaSatuan: 118797.35,
      totalHarga: 1425568.15,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN ===
    {
      id: 200,
      uraian: "Pekerjaan Pengelasan Line Up Pipa Baja Diameter s.d 2\"",
      satuan: "Joint",
      qty: 17,
      hargaSatuan: 552365.49,
      totalHarga: 9390213.41,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN KHUSUS/FINISHING ===
    {
      id: 300,
      uraian: "Dismantling Eksisting Filter",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 177300000,
      totalHarga: 177300000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN KHUSUS/FINISHING",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN DOKUMENTASI ===
    {
      id: 400,
      uraian: "Pekerjaan Laporan Harian",
      satuan: "hari",
      qty: 210,
      hargaSatuan: 75456.49,
      totalHarga: 15845863.16,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION ===
    {
      id: 500,
      uraian: "Pekerjaan Commissioning & Fasilitas Penanganan Keselamatan Kerja",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 51022814.02,
      totalHarga: 51022814.02,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // === DUMMY DATA: LNG PLANT ===
    {
      id: 1001,
      uraian: "Project Management LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 2100000000,
      totalHarga: 2100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    {
      id: 1002,
      uraian: "Ijin Lingkungan LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 150000000,
      totalHarga: 150000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === SUPPORTING WORK LNG PLANT ===
    {
      id: 1003,
      uraian: "Soil Investigation LNG Plant",
      satuan: "Titik",
      qty: 2,
      hargaSatuan: 90000000,
      totalHarga: 180000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PENYEDIAAN MATERIAL LNG PLANT ===
    {
      id: 1004,
      uraian: "Main Cryogenic Pipe",
      satuan: "m",
      qty: 100,
      hargaSatuan: 2500000,
      totalHarga: 250000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN LNG PLANT ===
    {
      id: 1005,
      uraian: "Pemasangan Equipment Utama",
      satuan: "Unit",
      qty: 5,
      hargaSatuan: 120000000,
      totalHarga: 600000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PEKERJAAN DOKUMENTASI LNG PLANT ===
    {
      id: 1006,
      uraian: "Dokumentasi Proyek LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 50000000,
      totalHarga: 50000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION LNG PLANT ===
    {
      id: 1007,
      uraian: "Commissioning LNG Plant",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 80000000,
      totalHarga: 80000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2020,
      infrastruktur: "Small-Scale Liquefaction Plant (100 - 800 TPD)",
      volume: 500,
      satuanVolume: "TPD",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "Small LNG Plant Bau Bau",
      lokasi: "Sulawesi",
      tipe: "LNG Plant"
    },
    // === DUMMY DATA: LNGC ===
    {
      id: 2001,
      uraian: "Project Management LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 3500000000,
      totalHarga: 3500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    {
      id: 2002,
      uraian: "Ijin Lingkungan LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 200000000,
      totalHarga: 200000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === SUPPORTING WORK LNGC ===
    {
      id: 2003,
      uraian: "Docking & Survey Kapal",
      satuan: "Kapal",
      qty: 1,
      hargaSatuan: 500000000,
      totalHarga: 500000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PENYEDIAAN MATERIAL LNGC ===
    {
      id: 2004,
      uraian: "Hull Plate",
      satuan: "Ton",
      qty: 2000,
      hargaSatuan: 12000000,
      totalHarga: 24000000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN LNGC ===
    {
      id: 2005,
      uraian: "Pemasangan Mesin Utama",
      satuan: "Unit",
      qty: 2,
      hargaSatuan: 800000000,
      totalHarga: 1600000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PEKERJAAN DOKUMENTASI LNGC ===
    {
      id: 2006,
      uraian: "Dokumentasi Kapal LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION LNGC ===
    {
      id: 2007,
      uraian: "Commissioning Kapal LNGC",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 150000000,
      totalHarga: 150000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "Big Scale LNGC > 100.000 m³",
      volume: 125000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 0,
      satuanKapasitas: "",
      proyek: "LNGC Papua",
      lokasi: "Kepulauan Riau",
      tipe: "LNGC"
    },
    // ...existing FSRU and other data...
  ],
  filterJenis: null,
};

const constractionCostSlice = createSlice({
  name: 'constractionCost',
  initialState,
  reducers: {
    setFilterJenis: (state, action) => {
      state.filterJenis = action.payload;
    },
    addProjectCosts: (state, action) => {
      // action.payload: array of items
      state.costs = [...state.costs, ...action.payload];
    },
    // reducer lain jika diperlukan
  },
});

export const { setFilterJenis, addProjectCosts } = constractionCostSlice.actions;
export default constractionCostSlice.reducer;
