import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  costs: [
    // === PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN ===
    {
      id: 1,
      uraian: "Project Management",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 1154296598,
      totalHarga: 1154296598,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 2,
      uraian: "Ijin MIGAS -  Certificate of Inspection (COI) PSV",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 25000000,
      totalHarga: 25000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 3,
      uraian: "Ijin Lingkungan",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 100000000,
      totalHarga: 100000000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 4,
      uraian: "Ijin Mendirikan Bangunan (IMB)",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 205500801,
      totalHarga: 205500801,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PROJECT MANAGEMENT DAN PEKERJAAN PERSIAPAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // === SUPPORTING WORK ===
    {
      id: 5,
      uraian: "Pekerjaan Soil Investigation + Laporan + Penentuan Kedalaman Pondasi",
      satuan: "Titik",
      qty: 1,
      hargaSatuan: 104250933.15,
      totalHarga: 104250933.15,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    {
      id: 6,
      uraian: "Pekerjaan Survey Lokasi dan Pembuatan Gambar",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 6728996.86,
      totalHarga: 6728996.86,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "SUPPORTING WORK",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PENYEDIAAN MATERIAL ===
    {
      id: 100,
      uraian: "Line Pipe, CS, ASME B36.10, ASTM A106, Sch 80, Gr.B, Bare Pipe, PE, Seamless, DRL, Dia. 1/2\"",
      satuan: "M'",
      qty: 12,
      hargaSatuan: 118797.35,
      totalHarga: 1425568.15,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PENYEDIAAN MATERIAL",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN PEMASANGAN DAN PENGUJIAN ===
    {
      id: 200,
      uraian: "Pekerjaan Pengelasan Line Up Pipa Baja Diameter s.d 2\"",
      satuan: "Joint",
      qty: 17,
      hargaSatuan: 552365.49,
      totalHarga: 9390213.41,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN PEMASANGAN DAN PENGUJIAN",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN KHUSUS/FINISHING ===
    {
      id: 300,
      uraian: "Dismantling Eksisting Filter",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 177300000,
      totalHarga: 177300000,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN KHUSUS/FINISHING",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN DOKUMENTASI ===
    {
      id: 400,
      uraian: "Pekerjaan Laporan Harian",
      satuan: "hari",
      qty: 210,
      hargaSatuan: 75456.49,
      totalHarga: 15845863.16,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN DOKUMENTASI",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
    // === PEKERJAAN COMMISSIONING & TRIAL OPERATION ===
    {
      id: 500,
      uraian: "Pekerjaan Commissioning & Fasilitas Penanganan Keselamatan Kerja",
      satuan: "Ls",
      qty: 1,
      hargaSatuan: 51022814.02,
      totalHarga: 51022814.02,
      aaceClass: 2,
      accuracyLow: -15,
      accuracyHigh: 20,
      kelompok: "PEKERJAAN COMMISSIONING & TRIAL OPERATION",
      tahun: 2023,
      infrastruktur: "Big Scale FSRU",
      volume: 200000,
      satuanVolume: "m³",
      kapasitasRegasifikasi: 250,
      satuanKapasitas: "MMSCFD",
      proyek: "FSRU Lampung",
      lokasi: "Jawa Timur",
      tipe: "FSRU"
    },
    // ...tambahkan data lain sesuai kelompok...
  ],
  filterJenis: null,
};

const constractionCostSlice = createSlice({
  name: 'constractionCost',
  initialState,
  reducers: {
    setFilterJenis: (state, action) => {
      state.filterJenis = action.payload;
    },
    // reducer lain jika diperlukan
  },
});

export const { setFilterJenis } = constractionCostSlice.actions;
export default constractionCostSlice.reducer;
